
// This file is generated automatically during PYLON build process
// DO NOT EDIT

#define PYLON_VERSION_MAJOR          3
#define PYLON_VERSION_MINOR          2
#define PYLON_VERSION_SUBMINOR       2
#define PYLON_VERSION_BUILD          3032
#define PYLON_VERSIONSTRING_MAJOR    "3"
#define PYLON_VERSIONSTRING_MINOR    "2"
#define PYLON_VERSIONSTRING_SUBMINOR "2"
#define PYLON_VERSIONSTRING_BUILD    "3032"

#define PYLON_VERSIONSTRING_COMMENT  "20121108 0843;GVMB0001;VC_GVD"
